export const FETCH_USER = 'FETCH_USER';
export const FETCH_RECOMMENDATIONS = 'FETCH_RECOMMENDATIONS';
export const FETCH_SEASONS = 'FETCH_SEASONS';
export const FETCH_LASTFLIGHT = 'FETCH_LASTFLIGHT';
export const FETCH_DIFFERENT_DESTINATIONS_COUNT = 'FETCH_DIFFERENT_DESTINATIONS_COUNT';
export const FETCH_TRANSACTIONSCOUNT = 'FETCH_TRANSACTIONSCOUNT';
export const FETCH_USER_INFOS = 'FETCH_USER_INFOS';
export const SPREAD_ID = 'SPREAD_ID';